### Configuration file for the soupault website generator ###

## Global settings

[settings]
  # Show build progress
  verbose = true

  # Show detailed debug information
  debug = false

  # Fail on page processing errors
  strict = true

  # Where generated files go
  build_dir = "build/"

  # Where page files are stored
  site_dir = "site/"

  # HTML page skeleton file to insert content into
  default_template_file = "templates/main.html"
  
  # ignore .draft files
  ignore_extensions = ["draft", "obsidian"]
  
  # Insert the content in <main>, after existing children (if any)
  default_content_selector = "div#content"
  default_content_action = "append_child"

  # Page considered the section index
  index_page = "index"

  page_file_extensions = ["html", "md"]
  doctype = "<!DOCTYPE html>"

  # Automatically load Lua plugins from plugins/
  # E.g. plugins/reading-time.lua is automatically loaded as "reading-time" widget.
  plugin_discovery = true
  plugin_dirs = ["plugins"]

[templates.tag-template]
  file = "templates/main_tag.html"
  content_selector = "div#content"
  content_action = "append_child"
  section = "blog/tag"
  
[templates.archive-template]
  file = "templates/main_archive.html"
  content_selector = "div#content"
  content_action = "append_child"
  page = "blog/index.md"

# Options in the [custom_options] table aren't soupault built-ins.
# It's a table for options that can be shared between multiple plugins.
[custom_options]

  # Number of "lastest post" to display on the main page
  blog_summary_max_entries = 10

  ## Atom feed settings
  atom_feeds = false

  # If you want to generate Atom feeds, you will need to adjust the site metadata config below:

  # Required:
  # site_url = "cerbi.neocities.org"

  # Optional but strongly recommended:
  # site_author = "Diana Cervi"
  # site_author_email = "oolongcat@protonmail.com"
  # site_title = "Cerbi"
  # site_logo = "https://cerbi.neocities.org/images/favicon.png"

  # Completely optional: 
  # site_subtitle = "Un blogghino"

[preprocessors]
  # Automatically call pandoc on every *.md page to conver it to HTML
  md = 'pandoc -f commonmark+smart -t html'

## Autogenerated section index settings
[index]
  index = true

  section = "blog/"

  sort_descending = true

  extract_after_widgets = ['make-post-header']

  sort_by = "date"

  # A directory with a .leaf file in it is treated as hand-made "clean URL",
  # rather than a section.
  leaf_file = ".leaf"

[index.fields]
  title = { selector = ["post-title", "h1"] }
  excerpt = { selector = ["post-excerpt", "p"] }
  date = { selector = ["#post-date", "time"] }
  tags = { selector = ".post-tag", select_all = true }
  update = { selector = "#last-update" }


[index.views.blog-index]
  # Insert generated index into an element that matches "#blog-index" selector.
  index_selector = "#blog-entries"

  # Only extract metadata from pages in site/blog/*
  section = "blog"

  # Jingoo template for rendering extracted metadata
  index_template = """
    {% for e in entries %}
	<div class=box><div class=inner>
    <h2><a href="{{e.url}}">{{e.title}}</a></h2>
    <div><strong>Pubblicato:</strong> {{e.date}}</div>
	{% if e.update %}
	 <div><strong>Aggiornato:</strong> {{e.update}}</div>
	 {% endif %}
    {% if e.tags %}
    <div class="post-tags">
       <strong>Categorie: </strong>
       {%- for t in e.tags -%}
         <a href="/blog/tag/{{t}}"><span class="post-tag">{{t}}</span></a>{% if not loop.last %}, {% endif %}
       {%- endfor -%}
    </div>
    {% endif %}
    <p>{{e.excerpt}}</p>
    <a href="{{e.url}}">Continua</a>
	</div></div>
    {% endfor %}
  """

  # Override soupault's built-in index processor with a custom Lua script.
  # That script is written to mimic the built-in indexer behavior,
  # it will take a template from the index_template option.
  file = "helpers/blog-index.lua"

# This view displays the first ten entries on the main page
[index.views.blog-summary]
  index_selector = "#latest-blog-entries"

  section = "blog"

  # In this case index_template is a soupault built-in
  index_template = """
    {% set limit = int(soupault_config.custom_options.blog_summary_max_entries) %}
    {% set limit = int(soupault_config.custom_options.blog_summary_max_entries) %}
    <dl>
      {% for e in sublist(0, limit, entries) %}
      <dt>{{e.date}}</dt>
      <dd> <a href="{{e.url}}">{{e.title}}</a> </dd>
      {% endfor %}
      </ul>
    </dl>
  """

## Widgets

# Takes the content of the first #page-title element or <h1> and inserts it into the <title>
# default is used if page has no elements matching those selectors.
[widgets.set-page-title]
  widget = "title"

  # Must run only after the header with an <h1 id="post-title"> element is inserted, which affects the blog section pages
  after = 'make-post-header'

  selector = ["#post-title", "h1"]
  default = "Cerbi"
  append = " &mdash; Cerbi"

# Inserts the contents of templates/header.html right before the <main> element
# There's a variety of actions, including prepend_child and replace_content
#[widgets.insert-header]
#  widget = "include"

#  selector = ".footnotes"
#  action = "insert_before"
#  file = "templates/header.html"

# Inserts the contents of templates/sidebar.html inside the sidebar element
# There's a variety of actions, including prepend_child and replace_content
[widgets.insert-sidebar]
  widget = "include"

  selector = ".page-wrapper"
  action = "prepend_child"
  file = "templates/sidebar.html"

# Inserts the contents of templates/title.html inside the title element
# There's a variety of actions, including prepend_child and replace_content
[widgets.insert-title]
  widget = "include"

  selector = ".title"
  action = "replace_content"
  file = "templates/title.html"

# Inserts the contents of templates/navbar.html inside the quick-nav element
# There's a variety of actions, including prepend_child and replace_content
[widgets.insert-navbar]
  widget = "include"

  selector = "body"
  action = "prepend_child"
  file = "templates/navbar.html"

# This widget comes from plugins/section-link-highlight.lua
# It highlights the "active" link in the navigation menu,
# that is, the link that matches the current page URL
[widgets.highlight-active-link]
  widget = "section-link-highlight"

  # Must run only after the header with a navigation menu is inserted
  after = ["insert-navbar"]

  selector = ".navbar"
  active_link_class = "nav-active"

# Inserts the contents of templates/footer.html at the end of the <body>
[widgets.insert-footer]
  widget = "include"
  selector = "body"
  action = "append_child"
  file = "templates/footer.html"

[widgets.make-post-header]
  after = "insert-title"
  widget = "post-header"
  section = "blog/"
  exclude_page = "blog/index.md"

  content_container_selector = "#content"

  post_header_template = '''
    <div id="post-header">
      <h1 id="post-title">{{title}}</h1>
      <div><strong>Pubblicato:</strong> <time id="post-date" datetime="{{date}}">{{date}}</time></div>
	  {% if update %}
	    <div><strong>Aggiornato:</strong> <time id="last-update" datetime="{{update}}">{{update}}</time></div>
		{% endif %}
      {% if tags %}
        <div class="post-tags">
         <span><strong>Categorie:</strong> </span>
         {%- for t in tags -%}
           <a href="/blog/tag/{{t}}"><span class="post-tag">{{t}}</span></a>{% if not loop.last %}, {% endif %}
         {%- endfor -%}
         </div>
		 <post-excerpt style="display:none;">{{excerpt}}</post-excerpt>
        {% endif %}
    </div>
'''



# Inserts a table of contents generated from page headings
[widgets.table-of-contents]
  #exclude_path_regex = '/index(.*)'

  widget = "toc"
  selector = "#generated-toc"

  min_level = 2

  toc_list_class = "toc"
  toc_class_levels = false

  valid_html = true

  numbered_list = true

  heading_links = true
  heading_link_text = "→ "
  heading_link_class = "here"

  use_heading_slug = true

[widgets.insert-comment-box]
  widget = "insert-if"

  selector = ".main"
  check_selector = "#archive"
  html = '<div id="blog-entries"></div>'

[widgets.insert-blog-entries]
  widget = "insert-if"

  selector = ".main"
  check_selector = "post-excerpt"
  html = '''
    <div class=box><div class=inner>
	  <div class="commentbox"></div>
	  <script src="https://unpkg.com/commentbox.io/dist/commentBox.min.js"></script>
	  <script>commentBox('5666845642194944-proj')</script>
  </div></div>'''
  action = ""
 
[widgets.insert-footnotes-container]
  widget = "insert-if"

  selector = "h4#footnotes"
  check_selector = "fn"
  html = '<ul id="footnotes"> </ul>'
  action = "insert_after"

[widgets.footnotes]
  widget = "footnotes"

  after = "insert-footnotes-container"

  selector = "ul#footnotes"
  footnote_selector = ["fn"]
  footnote_link_class = "footnote"
  footnote_template = "<li> </li>"
  back_links = true
  link_id_prepend = "footnote-"
  back_link_id_append = "-ref"

[widgets.atom]
  widget = "atom"
  page = "blog/index.md"
  feed_file = "atom.xml"
  use_section = "blog"
